// app/api/apps/[appId]/export/route.ts
// POST — Generates a full deployable Next.js project as a ZIP download

import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth/session";
import { prisma } from "@/lib/db";
import type { GenesisConfig, NormalizedField } from "@/lib/config/types";
import { buildSchema } from "@/lib/runtime/schemaBuilder";

async function resolveApp(appId: string, userId: string) {
  const app = await prisma.app.findUnique({ where: { id: appId } });
  if (!app) return { error: "App not found", status: 404 };
  if (app.userId !== userId) return { error: "Forbidden", status: 403 };
  return { app };
}

// ─── Code generators ──────────────────────────────────────────────────────────

function genPrismaSchema(config: GenesisConfig): string {
  const modelBlocks = config.models.map((model) => {
    const fields = model.fields
      .map((f) => {
        const prismaType =
          f.type === "number"
            ? "Float"
            : f.type === "boolean"
            ? "Boolean"
            : f.type === "date" || f.type === "datetime"
            ? "DateTime"
            : f.type === "multiselect" || f.type === "json"
            ? "Json"
            : "String";
        const optional = f.required ? "" : "?";
        const unique = f.unique ? " @unique" : "";
        const dflt =
          f.default != null
            ? ` @default(${typeof f.default === "string" ? `"${f.default}"` : f.default})`
            : "";
        return `  ${f.name}  ${prismaType}${optional}${unique}${dflt}`;
      })
      .join("\n");

    return `model ${model.name} {\n  id        String   @id @default(cuid())\n${fields}\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n}`;
  });

  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${modelBlocks.join("\n\n")}
`;
}

function genEnvExample(): string {
  return `# Database (PostgreSQL)
DATABASE_URL="postgresql://user:password@host:5432/dbname"

# NextAuth
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="your-secret-here-generate-with-openssl-rand-base64-32"

# Optional: OAuth providers
# GOOGLE_CLIENT_ID=""
# GOOGLE_CLIENT_SECRET=""
# GITHUB_ID=""
# GITHUB_SECRET=""
`;
}

function genReadme(appName: string, models: string[]): string {
  return `# ${appName}

Generated by [Genesis](https://genesis.app) — the metadata-driven app builder.

## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Set up environment variables
cp .env.example .env.local
# Edit .env.local and fill in DATABASE_URL

# Set up database
npx prisma db push

# Start dev server
npm run dev
\`\`\`

## Models

${models.map((m) => `- **${m}** — \`/api/${m.toLowerCase()}\``).join("\n")}

## API Endpoints

${models
  .map(
    (m) => `### ${m}
- \`GET  /api/${m.toLowerCase()}\`       — List all records (supports ?page=&search=)
- \`POST /api/${m.toLowerCase()}\`       — Create a record
- \`GET  /api/${m.toLowerCase()}/[id]\`  — Get record by ID
- \`PUT  /api/${m.toLowerCase()}/[id]\`  — Update record
- \`DELETE /api/${m.toLowerCase()}/[id]\` — Delete record`
  )
  .join("\n\n")}

## Tech Stack

- [Next.js 15](https://nextjs.org)
- [Prisma](https://prisma.io)
- [TypeScript](https://typescriptlang.org)
`;
}

function genPackageJson(appName: string): string {
  const slug = appName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return JSON.stringify(
    {
      name: slug,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        "db:push": "prisma db push",
        "db:studio": "prisma studio",
      },
      dependencies: {
        "@prisma/client": "^5.22.0",
        next: "15.1.0",
        react: "19.0.0",
        "react-dom": "19.0.0",
        "@paralleldrive/cuid2": "^2.2.2",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        prisma: "^5.22.0",
        typescript: "^5",
      },
    },
    null,
    2
  );
}

function genTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

function genNextConfig(): string {
  return `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;
}

function genDbLib(): string {
  return `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma =
  globalForPrisma.prisma ||
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
`;
}

function genModelApiRoute(modelName: string, fields: NormalizedField[]): string {
  const requiredFields = fields.filter((f) => f.required);
  const validationBlock = requiredFields
    .map(
      (f) =>
        `  if (!body.${f.name}) return NextResponse.json({ error: "${f.label} is required" }, { status: 400 });`
    )
    .join("\n");

  const createData = fields
    .map((f) => `      ${f.name}: body.${f.name} ?? undefined`)
    .join(",\n");

  const modelVar = modelName.charAt(0).toLowerCase() + modelName.slice(1);

  return `import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { createId } from "@paralleldrive/cuid2";

// GET /api/${modelVar} — list with pagination + search
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const page = Number(searchParams.get("page") ?? 1);
  const limit = Math.min(100, Number(searchParams.get("limit") ?? 20));
  const search = searchParams.get("search") ?? "";

  const where = search
    ? {
        OR: [
${fields
  .filter((f) => f.type === "text" || f.type === "email")
  .map((f) => `          { ${f.name}: { contains: search, mode: "insensitive" as const } }`)
  .join(",\n")}
        ],
      }
    : {};

  const [data, total] = await Promise.all([
    prisma.${modelVar}.findMany({
      where,
      skip: (page - 1) * limit,
      take: limit,
      orderBy: { createdAt: "desc" },
    }),
    prisma.${modelVar}.count({ where }),
  ]);

  return NextResponse.json({ data, total, page, totalPages: Math.ceil(total / limit) });
}

// POST /api/${modelVar} — create
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null);
  if (!body) return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });

${validationBlock}

  const record = await prisma.${modelVar}.create({
    data: {
      id: createId(),
${createData},
    },
  });

  return NextResponse.json({ data: record }, { status: 201 });
}
`;
}

function genModelIdApiRoute(modelName: string): string {
  const modelVar = modelName.charAt(0).toLowerCase() + modelName.slice(1);
  return `import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

type Params = { params: Promise<{ id: string }> };

// GET /api/${modelVar}/[id]
export async function GET(_req: NextRequest, { params }: Params) {
  const { id } = await params;
  const record = await prisma.${modelVar}.findUnique({ where: { id } });
  if (!record) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json({ data: record });
}

// PUT /api/${modelVar}/[id]
export async function PUT(req: NextRequest, { params }: Params) {
  const { id } = await params;
  const body = await req.json().catch(() => null);
  if (!body) return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });

  const record = await prisma.${modelVar}.update({ where: { id }, data: body }).catch(() => null);
  if (!record) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json({ data: record });
}

// DELETE /api/${modelVar}/[id]
export async function DELETE(_req: NextRequest, { params }: Params) {
  const { id } = await params;
  await prisma.${modelVar}.delete({ where: { id } }).catch(() => null);
  return new NextResponse(null, { status: 204 });
}
`;
}

function genAppLayout(appName: string): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${appName}",
  description: "Generated by Genesis",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: "system-ui, sans-serif", background: "#0f0f11", color: "#e2e8f0" }}>
        <nav style={{ borderBottom: "1px solid #1e1e2e", padding: "16px 32px", display: "flex", alignItems: "center", gap: "8px" }}>
          <span style={{ fontSize: "18px", fontWeight: 700, color: "#fff" }}>${appName}</span>
          <span style={{ fontSize: "12px", color: "#64748b", background: "#1e1e2e", padding: "2px 8px", borderRadius: "4px" }}>
            Generated by Genesis
          </span>
        </nav>
        <main style={{ maxWidth: "1200px", margin: "0 auto", padding: "32px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}
`;
}

function genGlobalCss(): string {
  return `*, *::before, *::after { box-sizing: border-box; }

body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
  background: #0f0f11;
  color: #e2e8f0;
}

table { width: 100%; border-collapse: collapse; }
th { text-align: left; padding: 12px 16px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; border-bottom: 1px solid #1e1e2e; }
td { padding: 12px 16px; font-size: 14px; color: #cbd5e1; border-bottom: 1px solid #1a1a2e; }
tr:hover td { background: rgba(255,255,255,0.03); }

input, select, textarea {
  background: #1a1a2e;
  border: 1px solid #2a2a3e;
  border-radius: 6px;
  color: #e2e8f0;
  font-size: 14px;
  padding: 8px 12px;
  width: 100%;
  outline: none;
}
input:focus, select:focus, textarea:focus { border-color: #4a6c6f; }

button {
  cursor: pointer;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  padding: 8px 16px;
  transition: opacity 0.15s;
}
button:hover { opacity: 0.85; }
button:disabled { opacity: 0.5; cursor: not-allowed; }

.btn-primary { background: #4a6c6f; color: #fff; }
.btn-danger  { background: #7f1d1d; color: #fca5a5; }
.btn-ghost   { background: transparent; border: 1px solid #2a2a3e; color: #94a3b8; }

.card { background: #12121a; border: 1px solid #1e1e2e; border-radius: 12px; padding: 24px; }
.badge { display: inline-block; font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 4px; }
`;
}

function genModelPage(
  modelName: string,
  fields: NormalizedField[],
): string {
  const modelVar = modelName.charAt(0).toLowerCase() + modelName.slice(1);
  const visibleFields = fields.filter(
    (f) => !f.hidden && f.name !== "id" && f.name !== "createdAt" && f.name !== "updatedAt"
  );

  return `"use client";
import { useState, useEffect, useCallback } from "react";

interface ${modelName}Record {
  id: string;
${visibleFields.map((f) => `  ${f.name}?: unknown;`).join("\n")}
  createdAt?: string;
}

export default function ${modelName}Page() {
  const [records, setRecords] = useState<${modelName}Record[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editRecord, setEditRecord] = useState<${modelName}Record | null>(null);
  const [form, setForm] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    const params = new URLSearchParams({ page: String(page), limit: "20" });
    if (search) params.set("search", search);
    const res = await fetch(\`/api/${modelVar}?\${params}\`);
    const data = await res.json();
    setRecords(data.data ?? []);
    setTotal(data.total ?? 0);
    setLoading(false);
  }, [page, search]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    const url = editRecord ? \`/api/${modelVar}/\${editRecord.id}\` : \`/api/${modelVar}\`;
    const method = editRecord ? "PUT" : "POST";
    await fetch(url, {
      method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    });
    setShowForm(false);
    setEditRecord(null);
    setForm({});
    fetchData();
    setSubmitting(false);
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Delete this record?")) return;
    await fetch(\`/api/${modelVar}/\${id}\`, { method: "DELETE" });
    fetchData();
  };

  const openEdit = (record: ${modelName}Record) => {
    setEditRecord(record);
    const f: Record<string, string> = {};
    ${visibleFields.map((f) => `f["${f.name}"] = String(record["${f.name}"] ?? "");`).join("\n    ")}
    setForm(f);
    setShowForm(true);
  };

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px" }}>
        <div>
          <h1 style={{ margin: 0, fontSize: "24px", fontWeight: 700 }}>${modelName}</h1>
          <p style={{ margin: "4px 0 0", color: "#64748b", fontSize: "14px" }}>{total} records</p>
        </div>
        <button className="btn-primary" onClick={() => { setEditRecord(null); setForm({}); setShowForm(true); }}>
          + Add ${modelName}
        </button>
      </div>

      <div style={{ marginBottom: "16px", display: "flex", gap: "12px" }}>
        <input
          placeholder="Search..."
          value={search}
          onChange={e => { setSearch(e.target.value); setPage(1); }}
          style={{ width: "280px" }}
        />
      </div>

      <div className="card" style={{ padding: 0, overflow: "hidden" }}>
        <table>
          <thead>
            <tr>
${visibleFields.map((f) => `              <th>${f.label}</th>`).join("\n")}
              <th style={{ textAlign: "right" }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={${visibleFields.length + 1}} style={{ textAlign: "center", padding: "40px", color: "#64748b" }}>Loading…</td></tr>
            ) : records.length === 0 ? (
              <tr><td colSpan={${visibleFields.length + 1}} style={{ textAlign: "center", padding: "40px", color: "#64748b" }}>No records yet</td></tr>
            ) : records.map(r => (
              <tr key={r.id}>
${visibleFields.map((f) => `                <td>{String(r["${f.name}"] ?? "—")}</td>`).join("\n")}
                <td style={{ textAlign: "right" }}>
                  <button className="btn-ghost" style={{ marginRight: "8px", fontSize: "12px", padding: "4px 10px" }} onClick={() => openEdit(r)}>Edit</button>
                  <button className="btn-danger" style={{ fontSize: "12px", padding: "4px 10px" }} onClick={() => handleDelete(r.id)}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {total > 20 && (
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "16px" }}>
          <span style={{ fontSize: "13px", color: "#64748b" }}>Page {page}</span>
          <div style={{ display: "flex", gap: "8px" }}>
            <button className="btn-ghost" onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}>← Prev</button>
            <button className="btn-ghost" onClick={() => setPage(p => p + 1)} disabled={records.length < 20}>Next →</button>
          </div>
        </div>
      )}

      {showForm && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50 }}>
          <div className="card" style={{ width: "480px", maxHeight: "90vh", overflowY: "auto" }}>
            <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "20px" }}>
              <h2 style={{ margin: 0 }}>{editRecord ? "Edit" : "New"} ${modelName}</h2>
              <button className="btn-ghost" style={{ padding: "4px 10px" }} onClick={() => { setShowForm(false); setEditRecord(null); }}>✕</button>
            </div>
            <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
${visibleFields
  .map(
    (f) => `              <div>
                <label style={{ fontSize: "12px", fontWeight: 600, color: "#94a3b8", display: "block", marginBottom: "6px" }}>
                  ${f.label}${f.required ? " *" : ""}
                </label>
                <input
                  type="${f.htmlInputType === "checkbox" ? "text" : f.htmlInputType}"
                  value={form["${f.name}"] ?? ""}
                  onChange={e => setForm(prev => ({ ...prev, "${f.name}": e.target.value }))}
                  required={${f.required}}
                  placeholder="${f.label}"
                />
              </div>`
  )
  .join("\n")}
              <button type="submit" className="btn-primary" disabled={submitting}>
                {submitting ? "Saving…" : editRecord ? "Update" : "Create"}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
`;
}

function genHomePage(config: GenesisConfig): string {
  const models = config.models;
  return `import Link from "next/link";

export default function HomePage() {
  const models = ${JSON.stringify(models.map((m) => ({ name: m.name, label: m.label ?? m.name, fieldCount: m.fields.length })))};

  return (
    <div>
      <div style={{ marginBottom: "32px" }}>
        <h1 style={{ fontSize: "32px", fontWeight: 700, margin: "0 0 8px" }}>${config.name}</h1>
        <p style={{ color: "#64748b", margin: 0 }}>${config.description ?? "Generated by Genesis"}</p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: "16px" }}>
        {models.map(m => (
          <Link key={m.name} href={\`/\${m.name.toLowerCase()}\`} style={{ textDecoration: "none" }}>
            <div className="card" style={{ cursor: "pointer", transition: "border-color 0.2s" }}
              onMouseEnter={e => (e.currentTarget as HTMLDivElement).style.borderColor = "#4a6c6f"}
              onMouseLeave={e => (e.currentTarget as HTMLDivElement).style.borderColor = "#1e1e2e"}>
              <div style={{ fontSize: "32px", marginBottom: "12px" }}>📊</div>
              <h3 style={{ margin: "0 0 4px", fontSize: "16px", fontWeight: 600, color: "#fff" }}>{m.label}</h3>
              <p style={{ margin: 0, fontSize: "13px", color: "#64748b" }}>{m.fieldCount} fields</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
`;
}

// ─── ZIP builder (pure JS — no external dep) ──────────────────────────────────
// We build a valid ZIP file in memory using raw bytes.

function uint32LE(n: number): number[] {
  return [n & 0xff, (n >> 8) & 0xff, (n >> 16) & 0xff, (n >> 24) & 0xff];
}
function uint16LE(n: number): number[] {
  return [n & 0xff, (n >> 8) & 0xff];
}

function crc32(buf: Uint8Array): number {
  const table = (() => {
    const t = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let j = 0; j < 8; j++) c = c & 1 ? (0xedb88320 ^ (c >>> 1)) : c >>> 1;
      t[i] = c;
    }
    return t;
  })();
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = table[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

interface ZipEntry {
  name: string;
  data: Uint8Array;
  crc: number;
  offset: number;
}

function buildZip(files: { name: string; content: string }[]): Uint8Array {
  const enc = new TextEncoder();
  const entries: ZipEntry[] = [];
  const parts: Uint8Array[] = [];
  let offset = 0;

  for (const file of files) {
    const nameBytes = enc.encode(file.name);
    const data = enc.encode(file.content);
    const crc = crc32(data);

    const localHeader = new Uint8Array([
      0x50, 0x4b, 0x03, 0x04, // signature
      0x14, 0x00,             // version needed: 2.0
      0x00, 0x00,             // flags
      0x00, 0x00,             // compression: store
      0x00, 0x00,             // mod time
      0x00, 0x00,             // mod date
      ...uint32LE(crc),
      ...uint32LE(data.length),
      ...uint32LE(data.length),
      ...uint16LE(nameBytes.length),
      0x00, 0x00,             // extra field length
      ...nameBytes,
    ]);

    entries.push({ name: file.name, data, crc, offset });
    parts.push(localHeader, data);
    offset += localHeader.length + data.length;
  }

  // Central directory
  const cdParts: Uint8Array[] = [];
  let cdSize = 0;
  const cdOffset = offset;

  for (const entry of entries) {
    const nameBytes = enc.encode(entry.name);
    const cd = new Uint8Array([
      0x50, 0x4b, 0x01, 0x02, // signature
      0x14, 0x00,             // version made by
      0x14, 0x00,             // version needed
      0x00, 0x00,             // flags
      0x00, 0x00,             // compression
      0x00, 0x00,             // mod time
      0x00, 0x00,             // mod date
      ...uint32LE(entry.crc),
      ...uint32LE(entry.data.length),
      ...uint32LE(entry.data.length),
      ...uint16LE(nameBytes.length),
      0x00, 0x00,             // extra
      0x00, 0x00,             // comment
      0x00, 0x00,             // disk start
      0x00, 0x00,             // int attrs
      0x00, 0x00, 0xa4, 0x81, // ext attrs (regular file 0o100644)
      ...uint32LE(entry.offset),
      ...nameBytes,
    ]);
    cdParts.push(cd);
    cdSize += cd.length;
  }

  // End of central directory
  const eocd = new Uint8Array([
    0x50, 0x4b, 0x05, 0x06,
    0x00, 0x00,
    0x00, 0x00,
    ...uint16LE(entries.length),
    ...uint16LE(entries.length),
    ...uint32LE(cdSize),
    ...uint32LE(cdOffset),
    0x00, 0x00,
  ]);

  const allParts = [...parts, ...cdParts, eocd];
  const total = allParts.reduce((s, p) => s + p.length, 0);
  const out = new Uint8Array(total);
  let pos = 0;
  for (const p of allParts) { out.set(p, pos); pos += p.length; }
  return out;
}

// ─── Route handler ─────────────────────────────────────────────────────────────

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ appId: string }> }
) {
  const { appId } = await params;
  const authResult = await requireAuth();
  if (authResult instanceof NextResponse) return authResult;

  const resolved = await resolveApp(appId, authResult.user.id);
  if ("error" in resolved) return NextResponse.json({ error: resolved.error }, { status: resolved.status });

  const { app } = resolved;
  const config = app.config as unknown as GenesisConfig;

  if (!config?.models?.length) {
    return NextResponse.json({ error: "App has no models. Generate the app first." }, { status: 400 });
  }

  const normalizedModels = buildSchema(config.models);
  const appSlug = app.name.toLowerCase().replace(/[^a-z0-9-]/g, "-");

  // Collect all files for the ZIP
  const files: { name: string; content: string }[] = [];

  // Root files
  files.push({ name: "package.json", content: genPackageJson(app.name) });
  files.push({ name: "tsconfig.json", content: genTsConfig() });
  files.push({ name: "next.config.ts", content: genNextConfig() });
  files.push({ name: ".env.example", content: genEnvExample() });
  files.push({ name: "README.md", content: genReadme(app.name, config.models.map((m) => m.name)) });
  files.push({ name: ".gitignore", content: "node_modules/\n.next/\n.env.local\n.env\n" });

  // Prisma
  files.push({ name: "prisma/schema.prisma", content: genPrismaSchema(config) });

  // lib/db.ts
  files.push({ name: "lib/db.ts", content: genDbLib() });

  // App layout + global CSS
  files.push({ name: "app/layout.tsx", content: genAppLayout(app.name) });
  files.push({ name: "app/globals.css", content: genGlobalCss() });
  files.push({ name: "app/page.tsx", content: genHomePage(config) });

  // Per-model: page + API routes
  for (const model of normalizedModels) {
    const modelSlug = model.name.toLowerCase();

    // Page
    files.push({
      name: `app/${modelSlug}/page.tsx`,
      content: genModelPage(model.name, model.fields),
    });

    // API: list + create
    files.push({
      name: `app/api/${modelSlug}/route.ts`,
      content: genModelApiRoute(model.name, model.fields),
    });

    // API: get/put/delete by id
    files.push({
      name: `app/api/${modelSlug}/[id]/route.ts`,
      content: genModelIdApiRoute(model.name),
    });
  }

  // Build ZIP — convert to Buffer so NextResponse accepts it as BodyInit
  const zipBytes = buildZip(files);
  const zipBuffer = Buffer.from(zipBytes);

  return new NextResponse(zipBuffer, {
    status: 200,
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${appSlug}-genesis.zip"`,
      "Content-Length": String(zipBuffer.length),
    },
  });
}
